/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */

function CreateHorizontalSlider(elementOrID, spec)
{
    var sliderElement = elementOrID;
    if (elementOrID.nodeType != Node.ELEMENT_NODE) {
        sliderElement = document.getElementById(elementOrID);
    }

	if (!sliderElement.loaded) {
		sliderElement.loaded = true;
        while (sliderElement.firstChild) {
            sliderElement.removeChild(sliderElement.firstChild);
        }

		var onchanged = spec.onchange || null;
		try { onchanged = eval(onchanged); } catch (e) { onchanged = null; }

		sliderElement.object = new AppleHorizontalSlider(sliderElement, onchanged);
        sliderElement.object.element = sliderElement;
		sliderElement.object.continuous = spec.continuous || false;
		sliderElement.object.setValue(spec.currentValue || 0);
        
        if (spec.originalID) {
            // when cloning template, refresh shortly after initialized
            var self = sliderElement;
            window.setTimeout(function() {self.object.refresh();}, 0);
        }
	}

	return sliderElement.object;
}
